#!/usr/bin/env python3
"""
Quick Setup Helper for Payment & Client Systems
Interactive guide for mobile setup on Galaxy Fold 6
"""

import os
import sys

print("=" * 80)
print("🚀 EchoPilot Payment & Client System - Quick Setup")
print("=" * 80)
print()

# Check current status
stripe_key = os.environ.get("STRIPE_SECRET_KEY")
stripe_webhook = os.environ.get("STRIPE_WEBHOOK_SECRET")
paypal_id = os.environ.get("PAYPAL_CLIENT_ID")
paypal_sec = os.environ.get("PAYPAL_SECRET")
client_db = os.environ.get("NOTION_CLIENT_DB_ID")
default_rate = os.environ.get("DEFAULT_RATE_USD_PER_MIN", "5.0")

payment_configured = (stripe_key and stripe_webhook) or (paypal_id and paypal_sec)
client_configured = bool(client_db)

print("📋 Current Status:")
print()

if payment_configured:
    provider = "Stripe" if stripe_key else "PayPal"
    print(f"✅ Payment System: {provider} configured")
else:
    print("❌ Payment System: Not configured")

if client_configured:
    print(f"✅ Client Management: Configured (Default rate: ${default_rate}/min)")
else:
    print("❌ Client Management: Not configured")

print()
print("=" * 80)

# Step-by-step guide
if not payment_configured:
    print("📱 STEP 1: Set Up Payment System")
    print("=" * 80)
    print()
    print("Choose ONE payment provider:")
    print()
    print("OPTION A: Stripe (Recommended) ⭐")
    print("  1. Go to: https://dashboard.stripe.com/apikeys")
    print("  2. Copy your 'Secret key' (starts with sk_)")
    print("  3. In Replit app → Tap ⋮ → Secrets → Add:")
    print("     Name: STRIPE_SECRET_KEY")
    print("     Value: sk_test_...")
    print()
    print("  4. Set up webhook:")
    print("     Go to: https://dashboard.stripe.com/webhooks")
    print("     Add endpoint: https://Echopilotai.replit.app/webhook/stripe")
    print("     Select events: checkout.session.completed, checkout.session.expired")
    print("     Copy signing secret (starts with whsec_)")
    print()
    print("  5. In Replit Secrets → Add:")
    print("     Name: STRIPE_WEBHOOK_SECRET")
    print("     Value: whsec_...")
    print()
    print("-" * 80)
    print()
    print("OPTION B: PayPal")
    print("  1. Go to: https://developer.paypal.com/dashboard")
    print("  2. Create or select your app")
    print("  3. Copy Client ID and Secret")
    print("  4. In Replit app → Tap ⋮ → Secrets → Add:")
    print("     Name: PAYPAL_CLIENT_ID")
    print("     Value: (your client ID)")
    print()
    print("     Name: PAYPAL_SECRET")
    print("     Value: (your secret)")
    print()
    print("     Name: PAYPAL_LIVE")
    print("     Value: false (or true for production)")
    print()
    print("  5. Set up webhook:")
    print("     Webhook URL: https://Echopilotai.replit.app/webhook/paypal")
    print("     Events: CHECKOUT.ORDER.APPROVED, CHECKOUT.ORDER.COMPLETED")
    print()
    print("=" * 80)
    print()

if not client_configured:
    print("📱 STEP 2: Set Up Client Management")
    print("=" * 80)
    print()
    print("1. CREATE NOTION DATABASE:")
    print("   • Open Notion (phone or computer)")
    print("   • Create new database (+ → Table)")
    print("   • Name: 'EchoPilot Clients'")
    print()
    print("2. ADD PROPERTIES:")
    print("   • Client Name (Title) - auto-created")
    print("   • Email (Email type)")
    print("   • Rate USD/min (Number type)")
    print("   • Active (Checkbox type)")
    print()
    print("3. ADD TEST CLIENT:")
    print("   • Client Name: Test Client")
    print("   • Email: your-email@example.com")
    print("   • Rate USD/min: 5.0")
    print("   • Active: ✅ checked")
    print()
    print("4. COPY DATABASE ID:")
    print("   • Open database as full page")
    print("   • URL looks like: notion.so/xxxxx?v=yyy")
    print("   • Copy the 'xxxxx' part (32 characters)")
    print()
    print("5. ADD TO REPLIT SECRETS:")
    print("   • Replit app → Tap ⋮ → Secrets → Add:")
    print("     Name: NOTION_CLIENT_DB_ID")
    print("     Value: (paste 32-char ID)")
    print()
    print("     Name: DEFAULT_RATE_USD_PER_MIN")
    print("     Value: 5.0")
    print()
    print("6. EXTEND JOB LOG DATABASE:")
    print("   • Open your Job Log database in Notion")
    print("   • Add these properties:")
    print()
    print("   REVENUE FIELDS:")
    print("   • Client (Relation → EchoPilot Clients)")
    print("   • Client Email (Email)")
    print("   • Client Rate USD/min (Number)")
    print("   • Gross USD (Number, 2 decimals)")
    print("   • Profit USD (Number, 2 decimals)")
    print("   • Margin % (Number, 1 decimal)")
    print()
    print("   PAYMENT FIELDS (if not present):")
    print("   • Payment Link (URL)")
    print("   • Payment Status (Select: Pending, Paid, Failed, Cancelled)")
    print()
    print("=" * 80)
    print()

if payment_configured and client_configured:
    print("🎉 BOTH SYSTEMS CONFIGURED!")
    print("=" * 80)
    print()
    print("✅ Payment system active")
    print("✅ Client management active")
    print()
    print("📊 What happens now:")
    print("  1. Jobs complete → Payment link created (3x AI cost)")
    print("  2. Revenue calculated (Duration × Client Rate)")
    print("  3. PDF invoice generated with payment link")
    print("  4. Invoice emailed to client automatically")
    print("  5. Webhook tracks when payment completes")
    print("  6. Nightly reconciliation (2:10 UTC)")
    print()
    print("🔗 Webhook URLs configured:")
    if stripe_key:
        print("  Stripe: https://Echopilotai.replit.app/webhook/stripe")
    if paypal_id:
        print("  PayPal: https://Echopilotai.replit.app/webhook/paypal")
    print()
    print("📖 Full documentation:")
    print("  • PAYMENT_SYSTEM_GUIDE.md")
    print("  • CLIENT_SYSTEM_GUIDE.md")
    print("  • SETUP_COMPLETE_GUIDE.md")
    print()

print("🧪 TEST YOUR SETUP:")
print("   Run: python test_integration.py")
print()
print("📊 CHECK CONFIGURATION:")
print("   Run: python autoconfig.py")
print()

if not payment_configured or not client_configured:
    print("⏭️  NEXT STEPS:")
    print("   1. Add secrets in Replit app (Tap ⋮ → Secrets)")
    print("   2. Create/configure Notion databases")
    print("   3. Run: python test_integration.py")
    print("   4. Check: python autoconfig.py")
    print()
    print("📱 The bot will auto-restart when you add secrets!")
    print()

print("=" * 80)
print("💡 TIP: Open SETUP_COMPLETE_GUIDE.md for full step-by-step instructions")
print("=" * 80)
