#!/bin/bash

echo "═══════════════════════════════════════"
echo "DEPLOY PRICING V7.0 - MANUAL STEPS"
echo "═══════════════════════════════════════"
echo ""
echo "Run these commands in your shell:"
echo ""
echo "cd levqor-site"
echo ""
echo "git add src/app/pricing/page.tsx"
echo "git add src/app/api/checkout/route.ts"
echo "git add src/app/api/notify-coming-soon/"
echo "git add scripts/"
echo "git add ../PHASE_7_PRICING_FINALIZED.md"
echo ""
echo "git commit -m 'v7.0: Competitive pricing with 4 tiers, trials, add-ons'"
echo ""
echo "git push origin main"
echo ""
echo "# Wait 2-3 minutes for Vercel to deploy, then test:"
echo "./scripts/test_checkout.sh"
echo ""
echo "═══════════════════════════════════════"
