#!/bin/bash
# Helper script to create Stripe Price IDs for Levqor plans
# Run this to generate the price IDs you'll need for STRIPE_PRICE_STARTER and STRIPE_PRICE_PRO

set -e

echo "=== Stripe Price Setup Helper ==="
echo ""
echo "This script will help you create Price IDs for:"
echo "  - Starter Plan: £19/month"
echo "  - Pro Plan: £49/month"
echo ""
echo "You need to create these in your Stripe Dashboard:"
echo ""
echo "1. Go to: https://dashboard.stripe.com/products"
echo ""
echo "2. Create 'Starter' Product:"
echo "   - Click 'Add product'"
echo "   - Name: Levqor Starter"
echo "   - Description: 1 project, email support, basic insights"
echo "   - Pricing: Recurring"
echo "   - Price: £19 / month"
echo "   - Click 'Save product'"
echo "   - Copy the Price ID (starts with 'price_')"
echo ""
echo "3. Create 'Pro' Product:"
echo "   - Click 'Add product'"
echo "   - Name: Levqor Pro"
echo "   - Description: Unlimited projects, priority support, advanced insights"
echo "   - Pricing: Recurring"
echo "   - Price: £49 / month"
echo "   - Click 'Save product'"
echo "   - Copy the Price ID (starts with 'price_')"
echo ""
echo "4. Add these secrets to your Replit project:"
echo "   - STRIPE_PRICE_STARTER=price_xxxxxxxxxxxxx"
echo "   - STRIPE_PRICE_PRO=price_xxxxxxxxxxxxx"
echo "   - SITE_URL=https://levqor.ai"
echo ""
echo "Once added, your checkout will work!"
