#!/bin/bash
# Quick Connector Setup Helper
# This script helps you configure Slack and Telegram connectors

echo "=== Levqor Connector Setup ==="
echo ""
echo "Current Status:"
curl -s http://localhost:5000/actions/health | python3 -c "import sys,json; data=json.load(sys.stdin); print('✅ Configured:', ', '.join([k for k,v in data['connectors'].items() if v])); print('❌ Missing:', ', '.join([k for k,v in data['connectors'].items() if not v]))"
echo ""
echo "================================"
echo ""
echo "To enable SLACK connector:"
echo "1. Visit: https://api.slack.com/messaging/webhooks"
echo "2. Click 'Create your Slack app' → 'From scratch'"
echo "3. Name your app (e.g., 'Levqor Notifications')"
echo "4. Enable 'Incoming Webhooks' and add to workspace"
echo "5. Copy the Webhook URL"
echo "6. Add to Replit Secrets: SLACK_WEBHOOK_URL"
echo ""
echo "================================"
echo ""
echo "To enable TELEGRAM connector:"
echo "1. Open Telegram and message: @BotFather"
echo "2. Send: /newbot"
echo "3. Follow prompts to name your bot"
echo "4. Copy the token (looks like: 123456789:ABCdef...)"
echo "5. Add to Replit Secrets: TELEGRAM_BOT_TOKEN"
echo "6. (Optional) Get your chat ID and add: TELEGRAM_CHAT_ID_DEFAULT"
echo ""
echo "================================"
echo ""
echo "Or use these quick commands:"
echo ""
echo "# For Slack (paste your webhook URL):"
echo "# replit secrets set SLACK_WEBHOOK_URL 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'"
echo ""
echo "# For Telegram (paste your bot token):"
echo "# replit secrets set TELEGRAM_BOT_TOKEN 'YOUR_BOT_TOKEN_HERE'"
echo ""
echo "After adding secrets, connectors will work immediately (no restart needed)."
